"""set table server change server to server_name

Revision ID: 1e0a8222cf06
Revises: 862741450667
Create Date: 2016-11-18 21:09:01.259999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e0a8222cf06'
down_revision = '862741450667'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('server_name', sa.Unicode(length=64), nullable=True))
    op.drop_column('server', 'server')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('server', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('server', 'server_name')
    ### end Alembic commands ###
