"""change table server id_user to user_id

Revision ID: 2ce11d4340cd
Revises: 6bae1be26de6
Create Date: 2016-11-18 09:49:00.832549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ce11d4340cd'
down_revision = '6bae1be26de6'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(u'server_ibfk_1', 'server', type_='foreignkey')
    op.create_foreign_key(None, 'server', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('server', 'id_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('id_user', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.create_foreign_key(u'server_ibfk_1', 'server', 'user', ['id_user'], ['id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.drop_column('server', 'user_id')
    ### end Alembic commands ###
