"""change table server user to username

Revision ID: 6bae1be26de6
Revises: c98cf632e225
Create Date: 2016-11-18 09:42:43.447593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bae1be26de6'
down_revision = 'c98cf632e225'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('username', sa.Unicode(length=64), nullable=False))
    op.drop_column('server', 'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('user', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('server', 'username')
    ### end Alembic commands ###
