"""set table server last_login_time default None

Revision ID: 862741450667
Revises: 2ce11d4340cd
Create Date: 2016-11-18 20:43:41.983039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862741450667'
down_revision = '2ce11d4340cd'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
